In [1]:
import numpy as np
import numpy.linalg as la

In [2]:
# simple matrix
m = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

In [3]:
m.shape

(2, 3)

In [4]:
np.eye(3, 3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [5]:
np.zeros((3, 3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [6]:
m = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [7]:
m[1, 1]

5

In [8]:
m[1, :]

array([4, 5, 6])

In [9]:
m[:, 0:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [10]:
m = np.array([
    [1, 2],
    [3, 4],
    [5, 6]
])
m.reshape((2, 3))

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
m.reshape((1, -1))

array([[1, 2, 3, 4, 5, 6]])

In [12]:
m.max(axis = 1)

array([2, 4, 6])

In [13]:
m.mean(axis = 0)

array([ 3.,  4.])

In [14]:
m.std(axis=0)

array([ 1.63299316,  1.63299316])

In [15]:
m.var(axis=0)

array([ 2.66666667,  2.66666667])

In [16]:
a = np.array([
    [1, 2],
    [3, 4]
])

In [17]:
a + a

array([[2, 4],
       [6, 8]])

In [18]:
a ** a

array([[  1,   4],
       [ 27, 256]])

In [19]:
a * a

array([[ 1,  4],
       [ 9, 16]])

In [20]:
a = np.array([
    [1, 2],
    [3, 4]
])

In [21]:
b = np.array([
    [1, 1, 1],
    [1, 1, 1]
])

In [22]:
a.dot(b)

array([[3, 3, 3],
       [7, 7, 7]])

In [23]:
import numpy.linalg as la

In [24]:
m = np.array([
    [1, 2],
    [3, 4]
])
m.T

array([[1, 3],
       [2, 4]])

In [25]:
evals, evects = la.eig(m)

In [26]:
U, s, V = np.linalg.svd(m)

In [27]:
np.array([0.1, 0.3, 0.1, 0.5])

array([ 0.1,  0.3,  0.1,  0.5])

In [28]:
p = np.array([0.1, 0.3, 0.1, 0.5])
length, = p.shape
length

4

In [29]:
p > 0.4

array([False, False, False,  True], dtype=bool)

In [31]:
p[p >= 0.1]

array([ 0.1,  0.3,  0.1,  0.5])

In [32]:
p.min()

0.10000000000000001

In [33]:
p.max()

0.5

In [34]:
p.argmax()

3

In [35]:
p.sort()

In [36]:
p = np.array([0.1, 0.3, 0.1, 0.5])
p.argsort()

array([0, 2, 1, 3])

In [37]:
events = np.array(['A', 'B', 'C', 'D'])

In [38]:
events

array(['A', 'B', 'C', 'D'],
      dtype='<U1')

In [39]:
i = p.argsort()[::-1]

In [40]:
i

array([3, 1, 2, 0])

In [41]:
p

array([ 0.1,  0.3,  0.1,  0.5])

In [42]:
events[i[:2]]

array(['D', 'B'],
      dtype='<U1')

In [43]:
events

array(['A', 'B', 'C', 'D'],
      dtype='<U1')

In [44]:
# Working with data
path = 'sample_test'
with open(path, 'w') as f:
    f.write('1, 2, 3')
np.genfromtxt(path, delimiter=',')

array([ 1.,  2.,  3.])

In [45]:
ls

numpy_tutorial.ipynb  sample_test


In [46]:
# Loading data from a matlab file with scipy

In [47]:
from scipy.io import loadmat

In [48]:
data = {}

In [49]:
loadmat(filename, data)

NameError: name 'filename' is not defined

In [50]:
data = np.array([1, 2, 3])

In [53]:
np.save('numpy_data', data)

In [56]:
ls

numpy_data.npy  numpy_tutorial.ipynb  sample_test


In [57]:
data = np.load('numpy_data.npy')

In [58]:
data

array([1, 2, 3])

In [59]:
m2 = np.arange(9).reshape((3, 3))

In [60]:
m2.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])